<<<<<<< HEAD
# Generated by Django 5.1.2 on 2025-09-04 01:57
=======
# Generated by Django 5.1.2 on 2025-03-23 23:56
>>>>>>> a337fb2a7f9fdba6e83f32597198a25237f90b9c

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kensaku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Primary_Item', models.CharField(max_length=200)),
                ('Tertiary_Item', models.CharField(max_length=200)),
                ('Item_No', models.IntegerField(blank=True, null=True)),
                ('Check_Item', models.CharField(max_length=200)),
                ('GL_importance', models.CharField(max_length=10)),
                ('M_GL_importance', models.CharField(max_length=10)),
                ('Test_Item', models.CharField(max_length=10)),
                ('Pic_need', models.CharField(max_length=10)),
                ('Shoken_No', models.CharField(max_length=10)),
                ('Shoken_Str', models.CharField(max_length=50)),
                ('Shoken_terms', models.CharField(max_length=200)),
                ('Water_terms1', models.CharField(max_length=10)),
                ('Handan1', models.CharField(max_length=10)),
                ('Judge1', models.CharField(max_length=10)),
                ('Water_terms2', models.CharField(max_length=10)),
                ('Handan2', models.CharField(max_length=10)),
                ('Judge2', models.CharField(max_length=10)),
                ('Tokutan', models.IntegerField()),
                ('Tandoku', models.IntegerField()),
                ('Gapei', models.IntegerField()),
                ('Shoken_No08', models.CharField(max_length=10)),
                ('Shoken_Str08', models.CharField(max_length=50)),
            ],
        ),
    ]
