# Generated by Django 5.2.6 on 2026-01-07 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kensaku', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kensaku',
            name='Water_terms1',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='kensaku',
            name='Water_terms2',
            field=models.CharField(max_length=15),
        ),
    ]
