# Generated by Django 5.2.6 on 2026-01-08 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kensaku', '0002_alter_kensaku_water_terms1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kensaku_Katasiki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JLK_MEISYO', models.CharField(max_length=20)),
                ('JLK_OEM_CD', models.CharField(max_length=20)),
                ('JLK_SYORIMEI', models.CharField(max_length=50)),
                ('JLK_SEINO', models.CharField(max_length=50)),
                ('MAKER_NM', models.CharField(max_length=30)),
                ('JLK_KATASUKI_LINK', models.CharField(max_length=100)),
            ],
        ),
    ]
