# Generated by Django 5.1.2 on 2026-01-09 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kensaku', '0003_kensaku_katasiki'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kensaku_katasiki',
            old_name='JLK_KATASUKI_LINK',
            new_name='JLK_KATASIKI_LINK',
        ),
    ]
