# Generated by Django 5.1.2 on 2026-01-09 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kensaku', '0004_rename_jlk_katasuki_link_kensaku_katasiki_jlk_katasiki_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kensaku_katasiki',
            name='JLK_KATASIKI_LINK',
            field=models.URLField(max_length=100),
        ),
    ]
