# Generated by Django 5.1.2 on 2026-01-23 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kensaku', '0006_alter_kensaku_katasiki_jlk_katasiki_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kensaku_katasiki',
            name='JLK_OEM_CD',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='kensaku_katasiki',
            name='JLK_SYORIMEI',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
