# Generated by Django 5.1.2 on 2026-02-19 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kensaku', '0007_alter_kensaku_katasiki_jlk_oem_cd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kensaku_katasiki',
            name='MAKER_NM_INDEX',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='kensaku_katasiki',
            name='JLK_OEM_CD',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
